GET http://localhost:3000/reserves

###

GET http://localhost:3000/reserves/2

###

POST http://localhost:3000/reserves HTTP/1.1
Content-Type: application/json

{
  "estat": "Pendent",
  "hora_inici": "2025-03-01T10:00:00Z",
  "hora_final": "2025-03-01T12:00:00Z",
  "data": "2025-03-01"
}

###

PUT http://localhost:3000/reserves/1 HTTP/1.1
Content-Type: application/json

{
  "estat": "Modificada",
  "hora_final": "2025-02-20T12:00:00Z"
}

###

DELETE http://localhost:3000/reserves/3 HTTP/1.1
